### ISSUE TITLE
[Feature] Board Post Detail implement

### ISSUE THREAD

**Issue by L-U-Ready** [Like-Lion-Team-WAY/WAY#49]
# 📑 작업 사항

게시글 상세보기 페이지 구현

게시글 수정, 삭제하려면 게시글 상세보기 페이지가 필요해서 Detail부터 구현하겠습니다.

게시글 상세보기 구현에 좋아요, 스크랩, 댓글 기능이  포함됩니다.

# To-do
- [x] 좋아요 기능 구현
- [x] 스크랩 기능 구현
- [ ] 댓글 기능 구현
- [ ] 게시글 상세보기

#  ETC
가능하면 게시글 수정, 삭제까지 해서 올리겠습니다.
